Document: txdbus
Title: Debian txdbus Manual
Author: <insert document author here>
Abstract: This manual describes what txdbus is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/txdbus/txdbus.sgml.gz

Format: postscript
Files: /usr/share/doc/txdbus/txdbus.ps.gz

Format: text
Files: /usr/share/doc/txdbus/txdbus.text.gz

Format: HTML
Index: /usr/share/doc/txdbus/html/index.html
Files: /usr/share/doc/txdbus/html/*.html
